renovatebot/docker-renovate

builder.json
depends on: renovatebot/renovate#6009
=> feat: add release config

.github/workflows/build.yml, Dockerfile
=> fix: add missing re2 build deps

.dockerignore, .github/workflows/build.yml, .github/workflows/configure-docker.sh, Dockerfile, README.md, bin/docker-entrypoint.sh, builder.json, package.json, yarn.lock
=> feat: use buildpack

Dockerfile
ref: renovatebot/docker-renovate-full#6
=> fix: remove python from final build

README.md, docs/gitlab.md
Some docs to configure gitlab.
ref enovatebot/config-help#636
=> docs: add gitlab sample

builder.json
=> chore: raise minimal version to 22.0.3

Dockerfile
=> feat: update node to v14.15.1

README.md, docs/bitbucket.md
Add some samples for bitbucket.org pipelines
=> docs: add bitbucket samples

Dockerfile
Can lead to issues which are very hard to find
=> fix: do not link duplicates

.github/workflows/build.yml, .github/workflows/cron.yml
See https://github.com/renovatebot/internal-tools/pull/261
=> ci: install sigstore

docs/gitlab.md
See https://github.com/renovatebot/renovate/discussions/11314#discussioncomment-2607416
=> docs: Demonstrate parallel Renovate jobs on GitLab

.github/workflows/build.yml, renovate.json
=> build: use github automerge

Dockerfile, bin/docker-entrypoint.sh
Use hardcoded node version for renovate executables
=> feat: pin node for renovate

README.md, docs/jenkins.md
As promised in https://github.com/containerbase/buildpack/discussions/370
=> docs: Add example for Jenkins pipeline (accessing self-hosted GitLab)

renovate.json
We've no lockfiles in this repo.
- https://github.com/renovatebot/renovate/issues/18543
=> chore: disable lockfile maintenance

builder.json
merge after renovate v35 and before other major tool updates
=> build: only rebuild v35

Dockerfile
- https://github.com/renovatebot/renovate/discussions/20854
- https://github.com/mend/renovate-on-prem/issues/258#issuecomment-1441990685
=> fix: explicit install npm

README.md, docs/bitbucket.md, docs/gitlab.md, docs/jenkins.md
All samples are now using the slim image with `binarySource=install` (default since v35)
=> docs: use install mode

.github/workflows/trivy.yml
Related:
- https://github.com/renovatebot/docker-renovate-full/pull/1722
- https://github.com/containerbase/base/pull/965
=> ci: use valid tag for trivy action

.github/workflows/build.yml, .github/workflows/trivy.yml, README.md, docs/bitbucket.md, docs/gitlab.md, docs/jenkins.md
=> feat!: publish as latest

.github/workflows/build.yml, builder.json
create multi arch images
- renovatebot/renovate#9229
- closes #249
=> feat: build arm64 / aarch64

.github/workflows/build.yml, renovate.json
=> ci: allow merge queue
